name: Terraform Multi Stage

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.13.1"

jobs:

  ##################################
  # DEV
  ##################################

  dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    environment: dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
          -var-file=environment/dev/terraform.tfvars \
          -out=dev.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve dev.tfplan

  ##################################
  # QA
  ##################################

  qa:
    name: Deploy QA
    runs-on: ubuntu-latest
    needs: dev
    environment: qa

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
          -var-file=environment/qa/terraform.tfvars \
          -out=qa.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve qa.tfplan

  ##################################
  # PROD
  ##################################

  prod:
    name: Deploy PROD
    runs-on: ubuntu-latest
    needs: qa
    environment: prod

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
          -var-file=environment/prod/terraform.tfvars \
          -out=prod.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve prod.tfplan